# This file was generated by GoReleaser. DO NOT EDIT.
cask "browzer" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "65922052a71889de9c10c32f59db58b6100ce5011e142a2c5b143fa37180e21e"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ea4fcf6b9fed5fa6b8e1e79292152539fb1e018f8f444b656e1d12ab158b3831"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad23e1274418ca7fd1bf8bc2963bb68f9d79c222d00301b0b3ae2cd47a5dfea3"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "234828c5950612e62297f230a254faba18893f106642d76163c75c0bc790fe99"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "browzer"
  desc "Hybrid vector + Graph RAG for your codebase"
  homepage "https://browzeremb.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "browzer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/browzer"]
    end
  end

  # No zap stanza required

end
