# This file was generated by GoReleaser. DO NOT EDIT.
cask "browzer" do
  version "4.2.1"

  on_macos do
    on_intel do
      sha256 "3a70346960b44294bb530539456b63c39922435a41e4f3fda94772eb5568fee6"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c3870657fc0d0fc5b081686b02a4c24e86a68fc8561e6e79b4f7918d1371a735"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "72e95e5eb5b5c1157e7781455aa2945b5457d281c3ff16288111db1d045c4918"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0a9b28bffa5adbe823306126cb89fd5ea19397ac4b00a652c3dda9850faf5f6d"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "browzer"
  desc "Hybrid vector + Graph RAG for your codebase"
  homepage "https://browzeremb.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "browzer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/browzer"]
    end
  end

  # No zap stanza required

end
