# This file was generated by GoReleaser. DO NOT EDIT.
cask "browzer" do
  version "1.5.2"

  on_macos do
    on_intel do
      sha256 "b39dee75ceeb64da98b014cbfdffc31805a29f66d6474b712509b14657695416"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2d643ec72b86d56efc56e00b60f27a152a0eb85d9074a50d67302369072f1e42"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "50ab3ee941cc9eb371e5fc8c2c683acee21bc27460c4c4943c052b0ac2fabbc4"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "31f1c08fb328d298eec55fa3cb18b4d41aef15a3ca353e920bedae0ddf4cbd9d"
      url "https://github.com/browzeremb/browzer-cli/releases/download/v#{version}/browzer-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "browzer"
  desc "Hybrid vector + Graph RAG for your codebase"
  homepage "https://browzeremb.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "browzer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/browzer"]
    end
  end

  # No zap stanza required

end
